#!/usr/bin/env python3
"""Browse and document a live OPC UA endpoint without guessing NodeIds."""
import argparse, asyncio, json, sys
from pathlib import Path
from datetime import datetime, timezone
from asyncua import Client, ua

DOMAIN_ENDPOINTS={
    'cargo':'opc.tcp://openplc-cargo:4840/openplc/opcua',
    'pms':'opc.tcp://openplc-pms:4840/openplc/opcua',
    'propulsion':'opc.tcp://openplc-propulsion:4840/openplc/opcua',
}

async def safe(call, default=None):
    try: return await call
    except Exception: return default

async def walk(node, depth, max_depth, out, seen):
    if depth > max_depth:
        return
    nodeid=node.nodeid.to_string()
    if nodeid in seen:
        return
    seen.add(nodeid)
    browse=await safe(node.read_browse_name(), None)
    dclass=await safe(node.read_node_class(), None)
    display=await safe(node.read_display_name(), None)
    dtype=None; access=None; value=None; status=None; source_ts=None; server_ts=None
    if dclass == ua.NodeClass.Variable:
        dt=await safe(node.read_data_type_as_variant_type(), None)
        dtype=getattr(dt,'name',str(dt)) if dt is not None else None
        al=await safe(node.read_attribute(ua.AttributeIds.AccessLevel), None)
        access=getattr(al,'Value',None)
        dv=await safe(node.read_data_value(), None)
        if dv is not None:
            try: value=dv.Value.Value
            except Exception: value=None
            try: status=str(dv.StatusCode)
            except Exception: status=None
            source_ts=getattr(dv,'SourceTimestamp',None)
            server_ts=getattr(dv,'ServerTimestamp',None)
    out.append({
        'depth':depth,
        'nodeid':nodeid,
        'browse_name':str(browse) if browse is not None else None,
        'display_name':getattr(display,'Text',str(display)) if display is not None else None,
        'node_class':getattr(dclass,'name',str(dclass)) if dclass is not None else None,
        'data_type':dtype,
        'access_level':str(access) if access is not None else None,
        'value':value,
        'status':status,
        'source_timestamp':source_ts.isoformat() if source_ts else None,
        'server_timestamp':server_ts.isoformat() if server_ts else None,
    })
    children=await safe(node.get_children(), [])
    for child in children:
        await walk(child, depth+1, max_depth, out, seen)

def render_md(endpoint, items):
    lines=[
        '# OPC UA Discovery Evidence','',
        f'Endpoint: `{endpoint}`','',
        f'Captured: `{datetime.now(timezone.utc).isoformat()}`','',
        '> Generated by browsing the live server. NodeIds are discovered, not assumed.','',
        '| NodeId | Browse name | Class | Data type | Status | Current value |','|---|---|---|---|---|---|'
    ]
    for x in items:
        if x['node_class']!='Variable': continue
        val=str(x['value']).replace('|','\\|')
        lines.append(f"| `{x['nodeid']}` | {x['browse_name'] or ''} | {x['node_class']} | {x['data_type'] or ''} | {x['status'] or ''} | `{val}` |")
    lines += ['', '## Commissioning checklist','',
              '- Confirm expected PLC variables appear.',
              '- Confirm each NodeId is mapped to the correct PLC symbol.',
              '- Record namespace URI/index before configuring Telegraf/FUXA.',
              '- Check status/Quality and timestamps, not only numeric values.',
              '- Do not copy example identifiers into production configuration without this discovery step.','']
    return '\n'.join(lines)

async def main_async(args):
    endpoint=args.endpoint or DOMAIN_ENDPOINTS[args.domain]
    async with Client(url=endpoint, timeout=args.timeout) as client:
        ns=await client.get_namespace_array()
        out=[]
        await walk(client.nodes.objects,0,args.depth,out,set())
    payload={'endpoint':endpoint,'namespace_array':ns,'captured_at':datetime.now(timezone.utc).isoformat(),'nodes':out}
    outdir=Path(args.outdir); outdir.mkdir(parents=True,exist_ok=True)
    (outdir/f'{args.domain}-opcua-discovery.json').write_text(json.dumps(payload,indent=2,default=str)+'\n')
    (outdir/f'{args.domain}-opcua-discovery.md').write_text(render_md(endpoint,out))
    print(json.dumps({'endpoint':endpoint,'namespaces':ns,'nodes':len(out),'output':str(outdir)},indent=2))

if __name__=='__main__':
    ap=argparse.ArgumentParser(description='Discover live OpenPLC OPC UA nodes and preserve commissioning evidence')
    ap.add_argument('domain',choices=DOMAIN_ENDPOINTS)
    ap.add_argument('--endpoint')
    ap.add_argument('--depth',type=int,default=6)
    ap.add_argument('--timeout',type=float,default=6.0)
    ap.add_argument('--outdir',default='/evidence/opcua')
    try:
        asyncio.run(main_async(ap.parse_args()))
    except Exception as e:
        print(f'OPC UA discovery failed: {e}',file=sys.stderr)
        raise SystemExit(2)
